### PR TITLE
[FEAT!] Replace death test (`d`) with crash (`c`) test

### PR DESCRIPTION
**Pull request by itislu**
**~[FIX] Fix syntax error exit code test cases~   
[FEAT] Replace death test (`d`) with crash (`c`) test**

- feat!: Replace death test (`d`) with crash (`c`) test
  The crash test contains all the tests which are out of subject and tests only for crashes, `vc` also tests for leaks. But no output is compared.

- feat!: Add a crash test and counter for all test cases

- feat: Restore all changed and deleted test cases
  They were changed or deleted because they are not part of the subject anymore. However, testing them should still not cause the minishell to crash or leak. Therefore, those test cases now only get checked for crashes and leaks, not for their outputs.

- improve!: Rename tester output dir to mstest_output_*
  This makes it more clear that the output is from this tester.

- improve: Count leaks as failed test cases

- improve: Center the result stats no matter the numbers

- fix: Fix no_env test not really testing without environment when testing with `a`

### CODE REVIEW

**Review by LeaYeh — CHANGES_REQUESTED** [review]
Need to keep the abnormal test cases

**Comment by itislu** [comment]
@LeaYeh This will require a review in person.
And if it's okay, I will also have to adjust the CI in minishell again.

**Review by LeaYeh — APPROVED** [review]

**Comment by LeaYeh** [comment]
Good to see you add more test cases

**Comment by itislu** [comment]
@LeaYeh What about this one? #37 was based on this one 😳

**Pull request merged**
